# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1676a2cafff287938c9cc10dbbb3d558a1952445ee96bf7bb1b390307e95a92431fafb99dcaaf8acbd6d98a29dc1786d94f87b2c723d1e43312b1ac8eb0bfc9f

test:
  secret_key_base: 55f2e263de04dd5405d6c188f5af9b66b9d3c5af7b80202a62866ed0b343105941b19009dc6e4804077572550f8915644ac8b65e6a4a4756d058b07ca227f27a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
